package com.essoft.imagetomath.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

//Green Color Scheme
val md_theme_light_primary = Color(0xFF006E1D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF92FA90)
val md_theme_light_onPrimaryContainer = Color(0xFF002204)
val md_theme_light_secondary = Color(0xFF52634F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E8CF)
val md_theme_light_onSecondaryContainer = Color(0xFF101F10)
val md_theme_light_tertiary = Color(0xFF38656A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBF1)
val md_theme_light_onTertiaryContainer = Color(0xFF002023)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D8)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF77DD77)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E1D)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF77DD77)
val md_theme_dark_onPrimary = Color(0xFF00390B)
val md_theme_dark_primaryContainer = Color(0xFF005314)
val md_theme_dark_onPrimaryContainer = Color(0xFF92FA90)
val md_theme_dark_secondary = Color(0xFFB9CCB3)
val md_theme_dark_onSecondary = Color(0xFF253423)
val md_theme_dark_secondaryContainer = Color(0xFF3B4B38)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E8CF)
val md_theme_dark_tertiary = Color(0xFFA0CFD4)
val md_theme_dark_onTertiary = Color(0xFF00363B)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D52)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBF1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF006E1D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF77DD77)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF77DD77)

//Red Color Scheme
val md_theme_red_primary = Color(0xFFAF2F2C)
val md_theme_red_onPrimary = Color(0xFFFFFFFF)
val md_theme_red_primaryContainer = Color(0xFFFFDAD6)
val md_theme_red_onPrimaryContainer = Color(0xFF410003)
val md_theme_red_secondary = Color(0xFF775653)
val md_theme_red_onSecondary = Color(0xFFFFFFFF)
val md_theme_red_secondaryContainer = Color(0xFFFFDAD6)
val md_theme_red_onSecondaryContainer = Color(0xFF2C1513)
val md_theme_red_tertiary = Color(0xFF725B2E)
val md_theme_red_onTertiary = Color(0xFFFFFFFF)
val md_theme_red_tertiaryContainer = Color(0xFFFEDEA6)
val md_theme_red_onTertiaryContainer = Color(0xFF261900)
val md_theme_red_error = Color(0xFFBA1A1A)
val md_theme_red_errorContainer = Color(0xFFFFDAD6)
val md_theme_red_onError = Color(0xFFFFFFFF)
val md_theme_red_onErrorContainer = Color(0xFF410002)
val md_theme_red_background = Color(0xFFFFFBFF)
val md_theme_red_onBackground = Color(0xFF201A19)
val md_theme_red_surface = Color(0xFFFFFBFF)
val md_theme_red_onSurface = Color(0xFF201A19)
val md_theme_red_surfaceVariant = Color(0xFFF5DDDB)
val md_theme_red_onSurfaceVariant = Color(0xFF534342)
val md_theme_red_outline = Color(0xFF857371)
val md_theme_red_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_red_inverseSurface = Color(0xFF362F2E)
val md_theme_red_inversePrimary = Color(0xFFFFB3AD)
val md_theme_red_shadow = Color(0xFF000000)
val md_theme_red_surfaceTint = Color(0xFFAF2F2C)
val md_theme_red_outlineVariant = Color(0xFFD8C2BF)
val md_theme_red_scrim = Color(0xFF000000)


val seed_red = Color(0xFFFF6961)
